java:
  stage: test
  script:
    - mvn compile
    - mvn test -s RunTCs/ReneFX/Main.xml
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
